---
- hosts: testenv
  become: true
  gather_facts: false
  vars:
    container_name: multi-docker-demo
    image_name: nithai/multi-docker-demo:latest
  
  tasks:
    - name: Get infos on container
      docker_container_info:
        name: '{{ container_name }}'
      register: result
      
    - name: displaying container info
      debug:
        var: result.exists

    - name: if container exists perform the following steps.
      block:
        - name: stopping provious version of container
          docker_container:
            name: '{{ container_name }}'
            state: stopped
        
        - name: removed stopped container 
          docker_container:
            name: '{{ container_name }}'
            state: absent

        - name: remove docker images
          docker_image:
            name: '{{ container_name }}'
            state: absent
      when: result.exists == true

    - name: Log into docker
      docker_login:
        username: username
        password: password
      
    - name: pulling the new image from docker hub
      docker_image:
        name: '{{ image_name }}'
        source: pull

    - name: creating a container
      docker_container:
        name: '{{ container_name }}'
        image: '{{ image_name }}'
        ports: "8090:8080"
        state: started