---
- name: User creation and changing password
  gather_facts: false
  hosts: localhost 
  become: true
  vars:
    username: "devops"
    password: "password"
  tasks:
  - name: Creating a new user "devops" and adding it to group sudo.
    user:
      name: "{{ username }}"
      comment: Devops user for automation
      generate_ssh_key: yes
      shell: /bin/bash
        
  - name: create password
    user:
      name: "{{ username }}"
      state: present
      password: "{{ password | password_hash('sha512') }}"

  - name: Add user to sudo file
    copy:
      dest: "/etc/sudoers.d/{{username}}"
      content: "{{ username }} ALL=(ALL) NOPASSWD:ALL"

  - name: Change ssh configuration
    lineinfile:
      dest: /etc/ssh/sshd_config
      regex: "^PasswordAuthentication"
      line: "PasswordAuthentication yes"
      state: present 
      validate: 'sshd -t -f %s'
      backup: yes
    
  - name: Restart sshd
    service:
      name: sshd
      state: restarted
