---
- name: User creation and changing password
  gather_facts: false
  hosts: all
  become: true
  vars:
    myuser: "devops"
    mypassword: "password"
  tasks:
  - name: Creating a new user "devops" and adding it to group sudo.
    user:
      name: "{{ myuser }}"
      comment: Devops user for automation
      shell: /bin/bash
        
  - name: create password
    user:
     name: "{{ myuser }}"
     state: present
     password: "{{ mypassword | password_hash('sha512') }}"