---
- hosts: all
  name: Creating a user
  tasks: 

  # name - Defines the username that is present or to create
	# groups - Adds users in secondary groups or use groups
	# state: present - Creates a user or works with a user
	# state: absent - Deletes a user
	# shell - Specifies shell-type a user can work on
	# home - Sets a user’s home directory (default=yes)
	# createhome: yes - Create a home directory for a user (default=yes)
	# createhome: no - Do not create a home directory for a user

  # Creating a user "devopsuser"
    - name: Creating a new user "devopsuser" and adding it to group sudo.
      ansible.builtin.user:
        name: "devopsuser"
        comment: devopsuser
        uid: 2000
        group: sudo
        shell: /bin/bash
        
