---
- name: Simple user creation and changing password
  hosts: all
  become: true
  vars:
    myuser: "devops"
    mypassword: "devops"
  tasks:
  - name: Creating a new user "devops" and adding it to group sudo.
    ansible.builtin.user:
      name: "{{ myuser }}"
      comment: devops user
      group: devops
      shell: /bin/bash
        
  - name: create password
    ansible.builtin.user:
     name: "{{ myuser }}"
     state: present
     password: "{{ mypassword | password_hash('sha512') }}"