--- 
- name: Creating a common user for Automation purpose. 
  hosts: all
  become: true
  vars:
    user_name: devops
    password: password
  tasks:    
    - name: Creating user
      user:
        name: '{{ user_name }}'
        comment: "Devops user for automation"
        generate_ssh_key: yes
        shell: /bin/bash

    - name: Changing user password
      user:
        name: '{{ user_name }}'
        state: present
        password: "{{ password | password_hash('sha512') }}"
      
    - name: Add user to sudo file
      copy:
        dest: "/etc/sudoers.d/{{user_name}}"
        content: "{{ user_name }} ALL=(ALL) NOPASSWD:ALL"
      
    - name: Exchange ssh keys
      authorized_key:
        user: devops
        state: present
        key: "{{lookup ('file', '/home/devops/.ssh/id_rsa.pub')}}"

    - name: Change ssh configuration
      lineinfile:
        dest: /etc/ssh/sshd_config
        regex: "^PasswordAuthentication"
        line: "PasswordAuthentication yes"
        state: present 
        validate: 'sshd -t -f %s'
        backup: yes
    
    - name: Restart sshd
      service:
        name: sshd
        state: restarted