---
- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: downloading Apache maven 
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz
        dest: /opt/test_dir/
    
    - name: untar the downloaded file
      unarchive:
        src: /opt/test_dir/apache-maven-3.8.5-bin.tar.gz
        dest: /opt/test_dir/