---
- hosts: jenkins-master
  become: yes
  remote_user: ec2-user
  become_user: root

  tasks:
  - name: updating the system
    yum:
      name: *
      state: latest

- name: Installing prerequisites
    yum:
      name: 
        - default-jdk
        - git
        - wget
        - unzip
      state: present

  - name: Importing the jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/debian-stable/jenkins.io.key
  
  - name: updating the system
    yum:
      name: *
      state: latest

  - name: Installing jenkins
    yum:
      name: jenkins
      state: latest

  - name: Start and enable service
    service: 
      name: jenkins
      state: started
      enabled: yes