---
- hosts: jenkinsMaster
  become: yes

  tasks:
  - name: updating the system
    yum:
      name: '*'
      state: latest

  - name: Installing prerequisites
    yum:
      name: 
        - java-11-openjdk-devel 
        - git
        - wget
        - unzip
      state: present
  
  - name: Downloading the jenkins repo
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Importing the jenkins key from url
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  
  - name: updating the system
    yum:
      name: '*'
      state: latest

  - name: Installing jenkins
    yum:
      name: jenkins
      state: latest

  - name: Start and enable service
    service: 
      name: jenkins
      state: started
      enabled: yes

  - name: Getting Jenkins Version
    shell: 'jenkins --version'
    register: jenkins_version

  - name: Jenkins Version
    debug: 
      msg: jenkins_version,stdout_lines

  - name: Display Admin password
    debug: 
      admin_pwd:  "{{ lookup ('file' , '/var/lib/jenkins/secrets/initialAdminPassword') }}"
     
