--- 
# install docker on Application servers
- hosts: app
  become: true
  gather_facts: false
  vars: 
    user_name: docker
    password: dockerpassword123
  tasks:
    - name: Remove all old docker packages
      yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent
    
    - name: installing yum-utils.
      yum: 
        name: yum-utils
        state: present

    - name: Adding docker repo
      yum_repository:
        name: docker-ce
        description: docker-ce yum yum_repository
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo

    - name: Installing Docker packages
      yum:
        name: docker
        state: present
    
    - name: starting and enabling docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Checking docker version
      shell: "docker --version"
      register: docker_version

    - debug:
        var: docker_version

    - name: create user
      user:
        name: '{{ user_name}}'
        group: docker

    - name: change password 
      user:
        name: '{{ user_name }}'
        state: present
        password: "{{ password | password_hash('sha512') }}"

    - name: create a dirctory and change permissions for docker images
      file:
       path: /opt/docker
       state: directory
       recurse: yes
       owner: docker
       group: docker
      