---
- hosts: all
  become: true
  name: Play to deploy ssh keys
  tasks:
  - name: Deploying keys
    authorized_key:
      user: vagrant
      state: present
      key: "{{lookup ('file', '/home/vagrant/.ssh/id_rsa.pub')}}"