---
- hosts: all
  become: true
  name: Play to deploy ssh keys
  tasks:
  - name: Deploying keys
    authorized_key:
      user: devops
      state: present
      key: "{{lookup ('file', '/home/devops/.ssh/id_rsa.pub')}}"