---
- name: Create user and deploy ssh keys 
  hosts: all
  become: true
  vars:
    username: 'devops'
    password: 'password'
    comment: 'Used for Automation'
  tasks:
  - name: Create a new user
    user:
      name: "{{ username }}"
      comment: "{{ comment }}"
      shell: /bin/bash
      state: present

  - name: create a password for the user
    user:
      name: "{{ username }}"
      state: present
      password: "{{ password | password_hash ('sha512') }}"

  - name: Adding the user to sudoers
    copy:
      dest: "/etc/sudoers.d/{{ username }}"
      content: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
  
  - name: Changing ssh configuration
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication yes"
      state: present
      validate: 'sshd -t -f %s'
      backup: yes
    
  - name: Restart ssh service 
    service: 
      name: sshd
      state: restarted