---
- name: Updating servers based on OS family
  hosts: all
  become: true
  tasks:
    - name: update Redhat server
      yum:
        name: "*"
        state: latest
        update_cache: true
      when: ansible_os_family == "RedHat"

    - name: update Ubuntu server
      apt:
        name: "*"
        state: latest
        update_cache: true
      when: ansible_os_family == "Debian"