--- 
# Deploying the war file created on jenkins and transfered over to Ansible.
- hosts: docker-build
  become: true
  tasks:
    - name: Deploying the .war file to tomcat servers.
      copy:
        src: /home/devops/artifacts/webapp/target/webapp.war
        dest: /opt/tomcat/apache-tomcat-9.0.62/webapps/
