---
- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (CentOS)
    yum:
      update_cache: yes
    changed_when: false

- hosts: all
  become: true
  roles:
    - prerequisite
