---
- hosts: localhost
  gather_facts: false
  tasks: 
    - name: create a new ec2 key pair
      ec2_key:
        name: Nithai_test
        region: "us-east-1"
      register: keypair_out
      when changed  = "False"

    - debug:
        var: keypair_out
    
    - name: Storing the key to a file 
      copy:
        content: "{{keypair_out.key.private_key}}"
        dest: ./Nithai.test.pem
      when: keypair_out.changed