---
- name: Deploy SQL file on DB server
  hosts: dbsrvgrp
  gather_facts: false
  tasks:
    - name: Copy SQL to dbsrv
      copy:
        src: files/db_backup.sql
        dest: /tmp/db_backup.sql
      tags:
        - deploy

    - name: Restoring DB
      mysql_db:
        name: accounts
        login_user: "{{ dbuser }}"
        login_password: "{{ dbpass }}"
        state: import
        target: /tmp/db_backup.sql
      notify: 
        - Restart_mysql
      tags:
        - deploy
  
  handlers:
    - name: Restart_mysql
      service:
        name: mysql
        state: restarted  
