---
- name: Build Artifact ROOT.war & SQL file to be copied in files/directory
  import_playbook: build.yml

- name: Set host to IP mapping in /etc/hosts file in all servers
  import_playbook: set_host_ip_map.yml

- name: Setup dbserver
  import_playbook: db.yml

- name: Deploy SQL file on DB server
  import_playbook: dbdeploy.yml

- name: Setup Memcached service
  import_playbook: memcached.yml

- name: Setup RabbitMQ service
  import_playbook: rabbitmq.yml

- name: Setup Tomcat Application server
  import_playbook: tomcat.yml

- name: Setup Nginx server
  import_playbook: nginx.yml

