---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Importing additional required variables
      include_vars: vars/output_vars
    
    - name: Importing additional required variables
      include_vars: vars/bastion_output_vars
    
    - name: Importing additional required variables
      include_vars: vars/stack_vars

    - name: create a new key pair, return generated private key
      ec2_key:
        name: "{{keypair_name}}"
        region: "{{region}}"
      register: ec2_keypair_output
      
    - name: Download the keypair
      copy:
        content: "{{ec2_keypair_output.key.private_key}}"
        dest: "{{keypair_name}}.pem"
        mode: 0400
      when: ec2_keypair_output.changed

    - name: security group for Load Balancer
      ec2_group:
        name: "{{name}}_lb_sg"
        description: allow http traffic from anywhere
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow http traffic from anywhere
        tags:
          Name: "{{name}} lb SG"
          Environment: "{{env}}"
          Resource owner: "{{res_owner}}"
          Team: "{{team}}"
      register: app_lb_sg_information

    - debug: 
        var: app_lb_sg_information

    - name: security group for Vprofile stack
      ec2_group:
        name: "{{name}}_app_sg"
        description: allow ssh traffic from everywhere and all ports within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: app_lb_sg_information.group_id
            rule_desc: allow http traffic from my load balancer
          
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{bastion_ec2_sg}}"
            rule_desc: allow ssh traffic from my IP
        tags:
          Name: "{{name}} app SG"
          Environment: "{{env}}"
          Resource owner: "{{res_owner}}"
          Team: "{{team}}"
      register: app_sg_information

    - name: updating Vprofile stack security group with itself. 
      ec2_group:
        name:  "{{name}}_app_sg"
        description: allow ssh traffic from everywhere and all ports within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        prune_rules: no
        rules:
          - proto: all
            group_id: "{{name}}_app_sg_information.group_id"
            rule_desc: allow all traffic within the group
        tags:
          Name: "{{name}} app SG"
          Environment: "{{env}}"
          Resource owner: "{{res_owner}}"
          Team: "{{team}}"
      register: app_sg_update_information