---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Importing additional required variables
      include_vars: vars/output_vars
    
    - name: Importing additional required variables
      include_vars: vars/bastion_output_vars
    
    - name: Importing additional required variables
      include_vars: vars/stack_vars
    
    
    - name: gather ec2 instance information based on VPC id
      ec2_instance_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{vpcid}}"
      register: ec2_instance_information

    - debug:
        var: ec2_instance_information